### ISSUE TITLE
unable to compile with iron 0.6

### ISSUE THREAD

**Issue by anjumkaiser** [abonander/multipart#97]
Unable to compile with iron 0.6.0

`
error[E0277]: the trait bound `&mut iron::Request<'_, '_>: multipart::server::HttpRequest` is not satisfied
   --> src/bin/store-backend\server\routes\mod.rs:485:31
    |
485 |     let mut form_data = match Multipart::from_request(req) {
    |                               ^^^^^^^^^^^^^^^^^^^^^^^ the trait `multipart::server::HttpRequest` is not implemented for `&mut iron::Request<'_, '_>`
    |
    = note: required by `<multipart::server::Multipart<()>>::from_request`
`

**Comment by abonander** [comment]
I widened the Iron version range to include `0.6.x` and published that as `0.13.6`. It seems to work without any other changes.
