### ISSUE TITLE
examples/iron.rs fails to build with with rustc 1.12.1 (d4f39402a 2016-10-19)

### ISSUE THREAD

**Issue by ConnorGray** [abonander/multipart#52]
The build fails with this error:

error[E0277]: the trait bound `&mut iron::Request<'_, '_>: multipart::server::HttpRequest` is not satisfied
  --> src/main.rs:17:11
   |
17 |     match Multipart::from_request(request) {
   |           ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: required by `<multipart::server::Multipart<()>>::from_request`

error: aborting due to previous error

**Comment by ConnorGray** [comment]
Nevermind, had to learn about Cargo features.. Silly me..
